### ISSUE TITLE
nMosseVai nMosseRispondi non contano bene le mosse

### ISSUE THREAD

**Issue by Silvan87** [Silvan87/Confabula#1]
nAzioniVai è un comando utilizzabile in scene.js, ad ogni passo del giocatore (ovvero se esamina qualcosa o cambia scena), viene incrementato un contatore che farà scattare un'azione dopo un certo numero di passi. La prima volta che si innesca (ci sono delle condizioni da soddisfare) può concedere, per esempio, 2 passi anziché 1 solo come impostato, oppure concede sempre 2 passi anziché 1 solo. La soluzione migliore sarebbe ripensare la logica delle azioni e dei passi. Infine, anche il comando nAzioniRispondi è probabilmente difettoso.

**Comment by ghost** [comment]
Allora credo di aver trovato il bug:

Nel file interprete.js alla riga 318 sostituisci con:
    if (Azioni[gruppo][ia].passo == azione.passi)

azione.passi + 1 era il problema.

Per provare la soluzione aggiungere in scene.js alla riga 52 il codice di test:
    nAzioniVai(3, 1);
Ora si sposta di scena dopo esattamente 3 azioni.

**Comment by Silvan87** [comment]
No, non si risolve cosí, l'errore è subdolo: nAzioniVai _forse_ ha comportamenti diversi se messo nella scena generale o in una scena specifica, inoltre _forse_ si comporta in modo diverso se si innesca per la prima volta o si continua a rinnescarlo. Una prova semplice si può fare con l'esempio Cromwell: all'inizio vai a nord dall'abate e il conteggio è sempre corretto, aggiungengo "+1" poi diventa errato. In linea di massima non crea serio danno, la vera soluzione sarebbe ripensare il modo in cui vengono contate le mosse.

L'attuale anomalia la si ottiene inserendo la variabile (o bandierina) "drekann" insieme alla variabile "inizio": scene.js, riga 92, cosí: _variabili("inizio|drekann"); in questo modo il drago viene subito a cercarti e quando ti trova dovresti poter fare solo 1 mossa, invece ne puoi fare 2, questa è un'anomalia che non ho capito perché si genera (dato che la situazione è del tutto analoga a quella dell'abate o del drago che funzionano).

**Comment by ghost** [comment]
In testa avrei un'idea magari ti puo essere utile:

potrebbe essere interessante nell'interprete mantenere sempre il numero di azioni totali compiute dal giocatore per ogni mossa. 

Quando si usano comandi come nAzioniVai si puo congelare da una parte (tipo stack) il numero di azioni in quel momento.

N = numero di azioni per ogni mossa, T = numero di azioni al momento della chiamata a nAzioniVai. 
Per ogni mossa nuova si fa N - T e si ottiene il numero di azioni compiute a partire dalla chiamata.

Non so se lo hai gia pensato cosi, ma potrebbe essere un meccanismo generalizzato per qualsiasi comando che richiede il conteggio dei passi.

**Comment by Silvan87** [comment]
Sí, implementerò questa soluzione, è pulita. Al momento c'è un contatore per ogni "azione ritardata" (le ho chiamate cosí quelle che scattano dopo n mosse), ma è meno sobria come scelta. Attualmente ho reso gestibile l'errore di nAzioniVai o nAzioniRispondi. La soluzione pratica è che quando si verifica l'anomalia, nell'argomento di nAzioniQualcosa relativo al numero di passi, si mette "numero di passi voluto" + 1, altrimenti si lascia solo il "numero di passi voluto". L'anomalia resta, ma almeno è gestibile.

**Comment by ghost** [comment]
Una domanda, l'ultimo commit ha risolto il bug? Se sì penso che puoi segnalare questo issue come chiuso.

**Comment by Silvan87** [comment]
No, le azioni sono state rinominate in nMosseVai ed nMosseRispondi, però non ho ancora implementato il nuovo modo di contare le mosse e si è conservato l'errore nella sua forma gestibile.

**Comment by Silvan87** [comment]
La gestione delle istruzioni nelle scene è stata completamente riscritta e gli eventi che scattano dopo un certo numero di mosse sono stati riconcepiti ed ora funzionano.
